name: kafka-prod

services:

  kafka:
    image: apache/kafka:4.2.0
    restart: unless-stopped
    ports:
      - "29092:9092"
    environment:
      # KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # listeners
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # controller quorum
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # ajustes
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    networks:
      kafka-prod-net:
        aliases:
          - kafka
      ms-net:
        aliases:
          - kafka

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.9.0
    restart: unless-stopped
    command:
      - --kafka.server=kafka:9092
    depends_on:
      - kafka
    ports:
      - "29308:9308"
    networks:
      kafka-prod-net:
        aliases:
          - kafka-exporter
      ms-net:
        aliases:
          - kafka-exporter

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    ports:
      - "28085:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: prod
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - kafka-prod-net

networks:
  kafka-prod-net:
    name: kafka-prod-net

  ms-net:
    external: true
    name: ms-net

