ALTER TABLE productos
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN id_categoria BIGINT NOT NULL,
    ADD COLUMN precio DECIMAL(12, 2) NOT NULL DEFAULT 0.01 AFTER id_categoria,
    ADD COLUMN stock INT NOT NULL DEFAULT 0 AFTER precio,
    ADD COLUMN activo TINYINT(1) NOT NULL DEFAULT 1 AFTER stock,
    ADD COLUMN sku VARCHAR(50) NULL AFTER activo;
