CREATE DATABASE IF NOT EXISTS db_auth;
CREATE DATABASE IF NOT EXISTS db_catalogo;
CREATE DATABASE IF NOT EXISTS db_producto;
CREATE DATABASE IF NOT EXISTS db_pedido;
CREATE DATABASE IF NOT EXISTS db_pago;
CREATE DATABASE IF NOT EXISTS db_carrito;
