server:
  port: ${PORT:7091}

spring:
  cloud:
    gateway:
      routes:
        # AUTH
        - id: auth-route
          uri: lb://auth
          predicates:
            - Path=/auth/**

        - id: catalogo-route
          uri: lb://catalogo
          predicates:
            - Path=/api/v1/categorias/**
        - id: catalogo-instancia
          uri: lb://catalogo
          predicates:
            - Path=/api/v1/catalogo/instancia

        # PRODUCTO
        - id: producto-route
          uri: lb://producto
          predicates:
            - Path=/api/v1/productos/**
        - id: producto-instancia
          uri: lb://producto
          predicates:
            - Path=/api/v1/producto/instancia

        - id: pedido-route
          uri: lb://pedido
          predicates:
            - Path=/api/v1/pedidos/**
        - id: pedido-instancia
          uri: lb://pedido
          predicates:
            - Path=/api/v1/pedido/instancia

        - id: pago-route
          uri: lb://pago
          predicates:
            - Path=/api/v1/pagos/**
        - id: pago-instancia
          uri: lb://pago
          predicates:
            - Path=/api/v1/pago/instancia

        - id: carrito-route
          uri: lb://carrito
          predicates:
            - Path=/api/v1/carritos/**
        - id: carrito-instancia
          uri: lb://carrito
          predicates:
            - Path=/api/v1/carrito/instancia

eureka:
  instance:
    hostname: ${RENDER_SERVICE_NAME:gateway}
    non-secure-port: ${PORT:7091}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:registry-server}:${EUREKA_PORT:7081}/eureka

jwt:
  secret: ${JWT_SECRET}
  issuer: auth

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
